version: '3.8'
services:
  backend:
    image: jonatasflima/tcc-match-backend:latest
    env_file:
      - backend.env
    ports:
      - 80:8080
    depends_on:
      - db
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - tcc_match_network

  db:
    image: postgres:11.14
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - tcc_match_data:/var/lib/postgresql/data
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - tcc_match_network

volumes:
  tcc_match_data:

networks:
  tcc_match_network:
